### ISSUE TITLE
Confusing for calculation of cross triggers rate.

### ISSUE THREAD

**Issue by Bovey0809** [audioanalytic/psds_eval#2]
Thanks for your great work. I came across some issues.

in `_confusion_matrix_and_rates`
shape(ct_rate) == (num_real_class, num_real_class)
len(class_names_set_no_world) = len(class_names_world_end) - 1 = num_real_class

```python
for i, cls in enumerate(class_names_set_no_world):
    for j, ocls in enumerate(cls_names_world_end):
        ct_rate[i, j] = ...
```

The j could be `len(class_names_world_end)`, and then `ct_rate[j]` will raise an index error.
How to solve such kind of problem. Is it a bug?

**Comment by tgrainge** [comment]
Hi, @Bovey0809 

Normally `self.class_names` should always include the injected world label, which is added when the ground truth data is provided, so in theory `j` should never be > `n_real_classes`. However, your example seems to not be running like that. So that I can help work on a fix and reproduce the issue you are having would you be able to provide the file detections and ground truths that are causing this problem? 

Kind Regards
Tom

**Comment by Bovey0809** [comment]
Dear Tom

Thanks for answering the question, I am using the version 0.2.0, the latest version. And by following the github, I noticed that 

> metadata and ground_truth tables must have the same unique values in the "filename" column

But I found the metadata table in my code is empty. I'm trying to follow the logic to find the reason. By the way, I am trying to reproduce the dcase2020 baseline model following the github repo, so that I think it should be some config problems, or some files are missing. I'm trying to debug. 

[csvfiles.zip](https://github.com/audioanalytic/psds_eval/files/4643853/csvfiles.zip)
The detection and gt tables have been export to csv format. Thanks for helping me with the problem.

**Comment by Bovey0809** [comment]
By fixing the metadata table, I get the psds score. Thanks a lot.

**Comment by tgrainge** [comment]
@Bovey0809 

That certainly would explain why there is an issue with the class_names. However, it is not ideal that it took you all this time to discover a simple situation of invalid/empty metadata. I think we can improve the code in this respect. I will make an update so that the input tables are better checked in the future. 

Thank you for raising the issue.

**Comment by RicherMans** [comment]
Hey there, 
so is there a possibility to just filter or warn the user when calling `add_operating_point`, that the maximum offset of the provided dataframe is larger than the durations given in the metadata?

Otherwise, the current error as suggested in this thread is very cryptic and has little information to indicate the user that its the metadatas fault and not some WORLD class index.

**Comment by cbilen** [comment]
Hi,
Did I understand your comment correctly, would you like a clearer error message when a detection table has an event with 
offset > audio file duration ?
We can definitely look into that if you could give us a small example data which raises the error you mentioned.

**Comment by RicherMans** [comment]
Hey there @cbilen ,
Thanks for the quick answer. 
It appears to be that I was a bit too fast. After changing my metadata I didn't get the error thrown as mentioned above, but I am still unsure why exactly it is thrown.

I will debug that issue and let you know in the next few days.
Thanks again!

**Comment by RicherMans** [comment]
Alright, so after quite some time I figured out why my code was throwing an error.
The main error I encountered is `IndexError: index 0 is out of bounds for axis 0 with size 0` caused by `tp_ratio[i] = counts[i, i] / n_cls_gt[cls]` in `psds_eval/psds.py`.

First of all, I provide a minimal **working** example:

```python
import psds_eval
import pandas as pd

gt = pd.DataFrame(
    {
        'filename': 'a.wav',
        'onset': 0.,
        'offset': 4.,
        'event_label': 'fake'
    },
    index=[0])
durations = pd.DataFrame(
    {
        'filename': 'a.wav',
        'duration': 10.
    },
    index=[0])

detections = pd.DataFrame(
    {
        'filename': 'a.wav',
        'onset': 0.,
        'offset': 2.,
        'event_label': 'fake'
    },
    index=[0])

psds = psds_eval.PSDSEval(
    ground_truth=gt,
    metadata=durations,
    dtc_threshold=0.5,
    gtc_threshold=0.5,
    cttc_threshold=0.5,
)
thres_f1, _ = psds.compute_macro_f_score(detections)
print(f"F1 is {thres_f1}")
```

The above code runs with 0.4.0 psds_eval.

if we now change the detection output to include some other columns in the dataframe, i.e., 'whoops' (for most part its additional data in the dataframe) , as seen in the following:

```python
WRONG_DETECTIONS = pd.DataFrame(
    {
        'filename': 'a.wav',
        'onset': 0.,
        'offset': 2.,
        'event_label': 'fake',
        'whoops': 1
    },
    index=[0])
thres_f1, _ = psds.compute_macro_f_score(WRONG_DETECTIONS)
print(f"F1 is {thres_f1}")
```

However, if one just forgets to remove additional columns in the ground-truth or metadata dataframe, the above mentioned error is thrown.
As an example:

```python
gt = pd.DataFrame(
    {
        'filename': 'a.wav',
        'onset': 0.,
        'offset': 4.,
        'event_label': 'fake',
        'whoops': 1
    },
    index=[0])
durations = pd.DataFrame(
    {
        'filename': 'a.wav',
        'duration': 10.
    },
    index=[0])

psds = psds_eval.PSDSEval(
    ground_truth=gt,
    metadata=durations,
    dtc_threshold=0.5,
    gtc_threshold=0.5,
    cttc_threshold=0.5,
)
thres_f1, _ = psds.compute_macro_f_score(detections)
print(f"F1 is {thres_f1}")
```
yields `IndexError: index 0 is out of bounds for axis 0 with size 0`.

So may I ask @cbilen , would it be possible to directly either assert in psds_eval that there are **only** the four columns `filename`, `event_label` and on/offset? 
Just currently the behaviour is a bit unpredictable, as I mentioned above (detection can have extra columns, metadata/ground truth cannot).

Thanks for the good work !

**Comment by cbilen** [comment]
Hi @RicherMans,
Thank you for the detailed example, it makes things much more clearer. Yes there used to be a check on the GT table, not sure if it got disabled, but we can surely look into this to sort it out. It is probably an easy fix. It might have been missed, since GT tables with extra columns are not often encountered (it is given by task organizers in DCASE for example).

In the meantime, you may want to pass your ground truth table as:
```
psds = psds_eval.PSDSEval(
    ground_truth=gt[["filename", "onset", "offset", "event_label"]],
    metadata=durations,
    dtc_threshold=0.5,
    gtc_threshold=0.5,
    cttc_threshold=0.5,
)
```
as a workaround, just to make sure.

Kind regards

**Comment by cbilen** [comment]
It would also be helpful for us if you can copy your message and raise it as a separate issue, just to increase the visibility. Thanks.

**Comment by RicherMans** [comment]
Alright thanks, will do!
